import type { Metadata, Viewport } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import Navbars from "@/components/ui/Navbar";
import Provider from "./Provider";

//IBM font
const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ["thai", "latin"],
  variable: "--font-ibm-plex-sans-thai",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Make the browser give us the full usable area (handles notches & iOS)
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#000000" },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="th" className="h-full">
      <body
        className={[
          ibmPlexSansThai.variable,
          // Use dvh to handle dynamic browser UI (iOS Safari, Android Chrome)
          "min-h-dvh flex flex-col bg-background text-foreground antialiased font-sans",
        ].join(" ")}
      >
        <Provider>
          <Navbars />
          <main className="flex-1 min-h-0 overflow-auto">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}